/**
* This file was automatically generated by @cosmwasm/ts-codegen@latest.
* DO NOT MODIFY IT BY HAND. Instead, modify the source JSONSchema file,
* and run the @cosmwasm/ts-codegen generate command to regenerate this file.
*/

import { EncodeObject } from "@interchainjs/cosmos-types";
import { MsgExecuteContract } from "interchainjs/cosmwasm/wasm/v1/tx";
import { toUtf8 } from "@interchainjs/encoding";
import { AdminAddrResponse, CodeIdResponse, CodeIdType, Uint128, Binary, CreateWalletMsg, Guardians, MultiSig, Coin, Cw20Coin, ExecuteMsg, Addr, ProxyMigrationTxMsg, WalletAddr, CanonicalAddr, RelayTransaction, FeeResponse, GovecAddrResponse, InstantiateMsg, QueryMsg, WalletQueryPrefix, Duration, StakingOptions, WalletInfo, ContractVersion, WalletsOfResponse, WalletsResponse } from "./Factory.types";
export interface FactoryMsg {
  contractAddress: string;
  sender: string;
  createWallet: ({
    createWalletMsg
  }: {
    createWalletMsg: CreateWalletMsg;
  }, funds_?: Coin[]) => EncodeObject;
  updateProxyUser: ({
    newUser,
    oldUser
  }: {
    newUser: Addr;
    oldUser: Addr;
  }, funds_?: Coin[]) => EncodeObject;
  migrateWallet: ({
    migrationMsg,
    walletAddress
  }: {
    migrationMsg: ProxyMigrationTxMsg;
    walletAddress: WalletAddr;
  }, funds_?: Coin[]) => EncodeObject;
  updateCodeId: ({
    newCodeId,
    ty
  }: {
    newCodeId: number;
    ty: CodeIdType;
  }, funds_?: Coin[]) => EncodeObject;
  updateWalletFee: ({
    newFee
  }: {
    newFee: Coin;
  }, funds_?: Coin[]) => EncodeObject;
  updateGovecAddr: ({
    addr
  }: {
    addr: string;
  }, funds_?: Coin[]) => EncodeObject;
  updateAdmin: ({
    addr
  }: {
    addr: string;
  }, funds_?: Coin[]) => EncodeObject;
}
export class FactoryMsgComposer implements FactoryMsg {
  sender: string;
  contractAddress: string;
  constructor(sender: string, contractAddress: string) {
    this.sender = sender;
    this.contractAddress = contractAddress;
    this.createWallet = this.createWallet.bind(this);
    this.updateProxyUser = this.updateProxyUser.bind(this);
    this.migrateWallet = this.migrateWallet.bind(this);
    this.updateCodeId = this.updateCodeId.bind(this);
    this.updateWalletFee = this.updateWalletFee.bind(this);
    this.updateGovecAddr = this.updateGovecAddr.bind(this);
    this.updateAdmin = this.updateAdmin.bind(this);
  }
  createWallet = ({
    createWalletMsg
  }: {
    createWalletMsg: CreateWalletMsg;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          create_wallet: {
            create_wallet_msg: createWalletMsg
          }
        })),
        funds: funds_
      })
    };
  };
  updateProxyUser = ({
    newUser,
    oldUser
  }: {
    newUser: Addr;
    oldUser: Addr;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_proxy_user: {
            new_user: newUser,
            old_user: oldUser
          }
        })),
        funds: funds_
      })
    };
  };
  migrateWallet = ({
    migrationMsg,
    walletAddress
  }: {
    migrationMsg: ProxyMigrationTxMsg;
    walletAddress: WalletAddr;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          migrate_wallet: {
            migration_msg: migrationMsg,
            wallet_address: walletAddress
          }
        })),
        funds: funds_
      })
    };
  };
  updateCodeId = ({
    newCodeId,
    ty
  }: {
    newCodeId: number;
    ty: CodeIdType;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_code_id: {
            new_code_id: newCodeId,
            ty
          }
        })),
        funds: funds_
      })
    };
  };
  updateWalletFee = ({
    newFee
  }: {
    newFee: Coin;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_wallet_fee: {
            new_fee: newFee
          }
        })),
        funds: funds_
      })
    };
  };
  updateGovecAddr = ({
    addr
  }: {
    addr: string;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_govec_addr: {
            addr
          }
        })),
        funds: funds_
      })
    };
  };
  updateAdmin = ({
    addr
  }: {
    addr: string;
  }, funds_?: Coin[]): EncodeObject => {
    return {
      typeUrl: "/cosmwasm.wasm.v1.MsgExecuteContract",
      value: MsgExecuteContract.fromPartial({
        sender: this.sender,
        contract: this.contractAddress,
        msg: toUtf8(JSON.stringify({
          update_admin: {
            addr
          }
        })),
        funds: funds_
      })
    };
  };
}